### ISSUE TITLE
Showing actual client IP in frontend logs

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#124]
Werkzeug shows IPs like 10.*.*.* for external users since it's behind a proxy.
I'm guessing this is because LoadBalancer services hide actual client IP due
to technical limitaitons

If frontend can be placed behind istio (#119), werkzeug can be configured to
read IPs from x-forwarded-for header. e.g.:

* https://blog.hartwork.org/?p=2655
* https://bugs.launchpad.net/openobject-server/+bug/1168243

I've noticed this because I have started getting attacker requests to endpoints
like /phpmyadmin instantly after deploying.

**Comment by Daniel-Sanche** [comment]
Is this only for istio, or would all deployments benefit from this?

**Comment by ahmetb** [comment]
Practically Istio and Knative would benefit immediately. But if you expose frontend via GKE Ingress, it can benefit directly as well. Plain GKE can't benefit as it uses Service.type=LoadBalancer. Since it has a fallback strategy, might be wise to implement.

**Comment by bourgeoisor** [comment]
Hi @ahmetb!

Is it the IPs in the wsgi logs that were incorrect? (Note: we have since reverted to gunicorn in commit https://github.com/GoogleCloudPlatform/bank-of-anthos/commit/368549b0edb4374765132fe21a87b91bcc37c295)

While the default Bank of Anthos deployment doesn't use istio, we do have a couple of [deployment options](https://github.com/GoogleCloudPlatform/bank-of-anthos#other-deployment-options) that _do_ use it, some of them being fairly new (i.e. newer than when this issue was filed).

I am also trying to understand the relevant of showing public IPs with regards to attackers being able to access admin endpoints. Could you add some more information, if this is still relevant?

**Comment by ahmetb** [comment]
The issue happens when we deploy this behind Knative Istio Cloud Run etc.

**Comment by bourgeoisor** [comment]
Doing some clean-up of issues. I don't think this is prioritized / actionable enough on our part, so I'll close it. Feel free to reopen if it still affect you!
On the protection side of things, we've enabled [Cloud Armour](https://cloud.google.com/armor) on our production environment and a variety of rules to mitigate XSS and harmful CVEs.
