### ISSUE TITLE
Python: Move pylint flags to config

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/bank-of-anthos#136]
## Description
We currently add several flags to pylint in the CI's Python Checkstyle step.   Moving this configuration to a config file would make it easier to maintain over time.

## Current Behavior
[smoke-tests.yml](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/.github/workflows/smoke-tests.yml)
```
   - name: Python Checkstyle
      timeout-minutes: 20
      run: |
        pylint --disable=F0401 --disable=W0511 --disable=E1101 --disable=R0801 --disable=R0903  ./src/*/*.py
        # disabled warnings: import loading, todos, function members, duplicate code, public methods
```

## Desired Behavior
```
   - name: Python Checkstyle
      timeout-minutes: 20
      run: |
        pylint 
```

## Open Questions
- [ ] should this be by service or for the entire project?

**Comment by rajatdiptabiswas** [comment]
Is this issue still available to be worked on?
Would you kindly let me know what needs to be done so that I can start working on it?

**Comment by bharathkkb** [comment]
Hi @rajatdiptabiswas 
Yes! Our goal is to move the flags to a .pylintrc file. IMO we can have just one that we can pass in via `--rcfile`. @Daniel-Sanche do you think we should just have a singular file for all py services or should we have one per service.

**Comment by Daniel-Sanche** [comment]
Either one works! We can probably stick with one global one for now to keep things simpler

@rajatdiptabiswas you would essentially need to add a .pylint file to the repo root, and adjust the command in the [smoke tests](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/master/.github/workflows/smoke-tests.yml) file to refer to it

**Comment by rajatdiptabiswas** [comment]
Thanks @Daniel-Sanche @bharathkkb 
I'll try my best to get it done

**Comment by rajatdiptabiswas** [comment]
Hello @Daniel-Sanche @bharathkkb 

I did the following:
1. Generated a default `.pylintrc` file using `pylint --generate-rcfile > .pylintrc` in the root directory
2. Removed all the default disable warnings from the `.pylintrc` file and added our own disable warning IDs instead from the `smoke-tests.yml` file
3. Updated the line in `smoke-tests.yml` file to `pylint --rcfile=./.pylintrc ./src/*/*.py`

I don't think it is necessary to add the `--rcfile=./.pylintrc` since the documentations say that it should find it automatically if it is in the root project directory, but I still left it there for your convenience.

The `Makefile` also has the `pylint --disable` flags. I have not touched that but do we remove those too?

Kindly let me know if these were the correct steps.

The default `.pylintrc` file has a lot of fields already set by default. I am not sure what all those fields do, so I am worried that I might break something. Is there any way I can test if everything is alright?

**Comment by rajatdiptabiswas** [comment]
I guess I shouldn't have sent the pull request to the `master` branch. Kindly let me know which branch should I make these changes to. 
I shall try to make the necessary changes as required.

**Comment by bharathkkb** [comment]
@rajatdiptabiswas thanks for the PR!

- targeting `master` is fine for the PR
>I don't think it is necessary to add the --rcfile=./.pylintrc 
- you are right about not needing `--rcfile`, i thought it made sense to explicitly call out where it came from since our workflow file with pylint command is in` .github/workflow` but its actually executed from the root.
>The Makefile also has the pylint --disable flags.
- yes, we should update these too

**Comment by rajatdiptabiswas** [comment]
Hi @bharathkkb!

Sure I'll make changes to the `master` branch itself then.

I think you're right about leaving the `--rcfile` flag. Better to be explicit and mention the `rcfile` location rather than not.

Things I should do be doing now:
1. Put the comments beside the disable codes as you mentioned [here](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/146#discussion_r415590059)
2. Remove the flags from the `Makefile` and change the line to `pylint --rcfile=./.pylintrc ./src/*/*.py` instead
3. Kindly confirm the structure of the `.pylintrc` file as well. Do I remove the defaults and just leave the disable portion as you mentioned [here](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/146#issuecomment-619798301)? I believe we'll need confirmation from @Daniel-Sanche for this matter.

Are these correct? If you give me the green light, I shall start working on these right away!

**Comment by rajatdiptabiswas** [comment]
I am closing my previous PR. Once you guys confirm all the requirements, I shall create a new PR and link it here.

Thanks!
