### ISSUE TITLE
Optimize Java container memory usage

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#188]

**Comment by Daniel-Sanche** [comment]
A couple notes for when I looked into this in the past:
- the Java services are caches, so some memory usage is expected. We can adjust the `CACHE_SIZE` environment variables to reduce memory if needed
- Java seems to use a large baseline of memory, even before adding caching on top. I had trouble getting it much lower, but maybe someone with more Java experience would have better luck
- There are issues getting the JVM to play nicely with containers. The `JVM_OPTS` environment variable is supposed to make it aware of resource limits and requests, but I'm not sure how much of a difference it makes

**Comment by bourgeoisor** [comment]
I'm looking into this alongside #521

**Comment by bourgeoisor** [comment]
I got it to a point where Java resources were low enough that BoA could be deployed on a default 3-node GKE cluster (rather than increasing the node count or machine type) in https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/712. It's probably as far as we can bring them without considerable Java effort / experience, so I'm going to close this for the time being, unless we want to revisit this later on.
