### ISSUE TITLE
Optimize Python docker image size

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#190]
contacts and userservice are > 300MB

**Comment by Daniel-Sanche** [comment]
We're using the [Google-recommended best practices](https://github.com/GoogleCloudPlatform/python-runtime#kubernetes-engine--other-docker-hosts) for secure python containers on GKE. Unfortunately the base image alone seems to be 358.77 MB on GCR, so if we want to get some headroom, we'll have to move away from that. But we'd preferrably want to make sure what we use is considered secure/approved for production (maybe alpine? distroless?)

**Comment by mathieu-benoit** [comment]
Hi @Daniel-Sanche and @askmeegs, curious to know if there is any updates on this since you started this discussion.

I think too that it would be great to have the base image as `python:3.7-slim` instead of `gcr.io/google-appengine/python`.

If we look at the current size of the images, we could see:
- In GCR: ~420MB
- Locally (so in Kubernetes): ~1.17GB

Having `python:3.7-slim` as base image will reduce both the size and the surface of attack/vulnerabilities of the 4 images: `frontend`, `userservice`, `loadgenerator` and `contacts`. 

Furthermore, we could find that 4 GCP examples/demos are not using this base image but are already leveraging `python:slim` instead:
- [`GoogleCloudPlatform/kubernetes-engine-samples/whereami`](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/whereami/Dockerfile)
- [`GoogleCloudPlatform/microservices-demo/emailservice`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/emailservice/Dockerfile)
- [`GoogleCloudPlatform/microservices-demo/recommendationservice`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/recommendationservice/Dockerfile)
- [`GoogleCloudPlatform/microservices-demo/loadgenerator`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/src/loadgenerator/Dockerfile)

Thoughts?

**Comment by bourgeoisor** [comment]
Commenting to reset OSLO. This is still something we should look at.
