### ISSUE TITLE
[Tracking] Contacts service has > 1s latency

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/bank-of-anthos#295]
<img width="684" alt="Screen Shot 2020-08-03 at 1 09 52 PM" src="https://user-images.githubusercontent.com/3137106/89208597-a6458b00-d58a-11ea-9d24-c519c064af06.png">

**Comment by djmailhot** [comment]
After fiddling with this for a long while, I'm inclined to believe **this unexpected latency is common to all our Python services**.  

I inserted HTTP calls to the /ready endpoint for the contactservice and the userservice, and both calls have large latencies even though the function is simply  `return "ok", 200`.
![frontend_trace_ready](https://user-images.githubusercontent.com/704680/93639415-cd76e100-f9ad-11ea-8f47-cc46e7876579.png)

**Comment by askmeegs** [comment]
Next steps: rule out - 

1. flask
2. gunicorn
3. running locally vs. in k8s

**Comment by djmailhot** [comment]
I've think I've found one other source of latency:  SQLAlchemy.

It turns out that [the SQLAlchemy ORM introduces overhead latency](https://anonbadger.wordpress.com/2010/09/09/optimizing-an-sqlalchemy-call/).  This can be avoided by using raw SQL calls instead.

The latency difference between raw SQL and SQL Alchemy seems to be around ~500ms
![frontend_latency_sqlalchemy](https://user-images.githubusercontent.com/704680/93649600-361b8900-f9c1-11ea-91f4-486652e7fef0.png)

The traces seem to indicate that this is contributing to the latency problem for the contacts service.

Trace using SQL Alchemy.
![sqlalchemy_trace](https://user-images.githubusercontent.com/704680/93649831-bb06a280-f9c1-11ea-96f9-5a5d5a7303e8.png)

Trace using raw SQL
![sql_trace](https://user-images.githubusercontent.com/704680/93649838-bf32c000-f9c1-11ea-9765-878a54e7b907.png)

The code for raw sql can be found under the GitHub branch `python-raw-sql`

**Comment by djmailhot** [comment]
## So far ruled out the following:

### SQL latency
**Hypothesis**:  SQL calls from the Python services are slow.  Calls not using SQL should be fast.

- Insert queries to `/ready` endpoints from the homepage (See branch `frontend-test-ready`)

**Result**:  Calls to `/ready` still have average ~500ms latencies.

### Threading & Scaling issues
**Hypothesis**:  Flask and Gunicorn aren't configured for maximum performance

- Flask `threaded=True`
- Gunicorn `workers=5 threads=2`

**Result**:  No effect.  This latency remains even when turning off the load generator and making one request a minute.

### K8 image
**Hypothesis**:  Python Dockerfiles use an image with baggage `gcr.io/google-appengine/python`

- Dockerfile `FROM python:3`

**Result**:  No effect.

**Comment by djmailhot** [comment]
Opened All Python services have very slow HTTP requests #356 to track the issue with uniform latencies across all Python services.

See Convert Python services to use raw SQL instead of the SQLAlchemy ORM #357 for fixing high latency SQL calls for contactservice (and userservice)

**Comment by askmeegs** [comment]
Closing this in favor of two sub-issues, which together should fix the python service latency.  #356  (Cloud Trace exporter latency) and #361  (SQLAlchemy latency)
