### ISSUE TITLE
HTTPConnectionPool errors in the frontend service for balancereader

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/bank-of-anthos#453]
Errors specific to `balancereader`
```
[ERROR] | home | Error getting account balance: HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/4365549432 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0b00661390>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**_GCP Cloud Logging Query:_**
```
resource.type="k8s_container"
resource.labels.project_id="<PROJECT_ID>"
resource.labels.location="<REGION>"
resource.labels.cluster_name="<CLUSTER>r"
resource.labels.namespace_name="<NAMESPACE>"
labels.k8s-pod/app="frontend"
"Error getting account balance: HTTPConnectionPool(host='balancereader', port=8080)"
```

**Comment by bourgeoisor** [comment]
I've deployed the latest commit of Bank of Anthos last night and let it run for 12+ hours.

I am indeed seeing those errors, but only during the first few seconds of Bank of Anthos getting deployed (assumedly because not all the Pods are running / ready yet and as thus there are some retries between those services):
![image](https://user-images.githubusercontent.com/3271352/128905947-5a00a75d-2de2-4dd5-af2c-92b10d851f4a.png)

That said, once all the Pods are ready, I am no longer seeing any HTTPConnectionPool errors at all. In fact, the only errors I am seeing at all past the first couple minutes of the services getting ready are from the frontend and the ledgerwriter:
![image](https://user-images.githubusercontent.com/3271352/128906133-31b1a526-b235-49a7-8625-3d8a25a1cca2.png)
And _those_ errors are only coming from the loadgen trying invalid banking transactions, which is normal:
![image](https://user-images.githubusercontent.com/3271352/128906209-f3e7a488-1f8f-4064-969d-e3658bad8433.png)

@Shabirmean can you confirm seeing those errors past the initial boot up / readying up process with the latest Bank of Anthos version, or were they just transient errors because Pods were not all in a ready state? If not, I suggest we close this issue as WAI.

**Comment by Shabirmean** [comment]
Thank you very much @bourgeoisor for working on reproducing this and testing it. As I can remember this was reported by a CE who was working with the sample + ACM. It could be that they saw it only during the startup of a new deploy. We have have this issue closed for now unless it's raised again
