### ISSUE TITLE
Integration with Anthos Identity Service

### ISSUE THREAD

**Issue by n0psn0ps** [GoogleCloudPlatform/bank-of-anthos#741]
### Describe request or inquiry 

I'd love to better understand how to integrate Anthos Identity Service. The details in the Google Cloud documentation are a little hard to digest. If it was integrated as a learning process, especially in a demo environment like Bank of Anthos. Mostly since it is easy getting everything up based on such a simple guide. I believe this would help increase the practical side of how to apply the Anthos google cloud environment.

### What purpose/environment will this feature serve? 

Education and security.

**Comment by arueth** [comment]
Anthos Identity Service(AIS) is primarily for integrating existing OIDC or LDAP authentication for accessing the Anthos clusters and not really the application itself. Are you looking to see AIS used for cluster authentication or application authentication?

**Comment by mathieu-benoit** [comment]
Hi @n0psn0ps, thanks for your interest.

Like @arueth, mentioned, AIS is about the authentication of your Anthos clusters, so it's more about how to integrate with your identity providers using protocols such as OIDC and LDAP in order to perform `kubectl` commands accordingly.

Here is some demos where you could see this in action: https://www.youtube.com/watch?v=Qh1zP-TF-d4.

Closing this for now because it's not directly related to this sample apps repo, but feel free to share more about your needs and feedback about that.

Thanks!
